import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";

export const runtime = "nodejs";

export async function POST(req) {
  try {
    const { title, content } = await req.json();

    if (!title || !content) {
      return new Response(JSON.stringify({ error: "Missing title or content." }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const paragraphs = content
      .split("\n")
      .filter((line) => line.trim().length > 0)
      .map(
        (line) =>
          new Paragraph({
            children: [new TextRun({ text: line.trim(), size: 22 })],
            spacing: { after: 200 },
          })
      );

    const doc = new Document({
      sections: [
        {
          children: [
            new Paragraph({
              text: title,
              heading: HeadingLevel.TITLE,
              spacing: { after: 100 },
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: "Draft generated by Mizan — for legal review, not final legal advice.",
                  italics: true,
                  size: 18,
                  color: "888888",
                }),
              ],
              spacing: { after: 300 },
            }),
            ...paragraphs,
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${title.replace(/[^a-z0-9]/gi, "_")}.docx"`,
      },
    });
  } catch (err) {
    console.error(err);
    return new Response(JSON.stringify({ error: "Could not generate document." }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}
